### PR TITLE
NIM-13492: DefaultActionExecutorUpdate Improvements

### PR DESCRIPTION
**Pull request by lopezton-anthem**
# Overview of Changes
```_update``` calls with a path to a collection param now supports surgical update of collection.

# Additional Info
To preserve existing functionality, the first attempts to update tries to transform the JSON payload into a "collection element". If the transformation is successful, it will be "added" to the collection (previous implementation).  If the transformation fails, it will attempt to transform the JSON payload into the collection element represented by the param path and attempt to "surgically" update each of the provided values.

To "surgically" update, means to update only explicit fields provided in the object tree. Fields that are not provided will retain existing values.

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @lopezton-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by lopezton-anthem** [comment]
@soham-anthem I know this is one scenario we talked about (as it's listed in the Jira issue)

Were there others that we needed to implement as part of this issue?

**Comment by lopezton-anthem** [comment]
Agree on the exception logic. I will see if we have support to avoid using exceptions to route the logic -- we should.

> **Scenario 3:** *param path is a collection param*
_update would be treated as an add of element to an existing collection

Regarding this **Scenario 3**, the change submitted splits it into two parts:

**Scenario 3-1**: *param path is a collection param **AND** the provided JSON is matching the __collection element type__ of that param*
_update would be treated as an add of element to an existing collection

**Scenario 3-2**: *param path is a collection param **AND** the provided JSON is matching the __collection type__ of that param*
_update would be treated same as _update to a nested param

**Comment by lopezton-anthem** [comment]
Regarding **Scenario 3-2**, I now realize a change is needed when invoking `_update` on a collection where the payload includes the removal of a collection element. For example, consider the collection of ints `[1, 2, 3]`, if we remove element '2' and send an `_update` with a JSON payload like `[1, 3]`, the framework would update the collection to `[1, 3, 3]`. If this scenario is valid, we need to include a way to support this.

Considering this, it would be easier to just treat it as a `_replace`.

**Comment by soham-anthem** [comment]
I think for Scenario 3, if the payload is an array and the path points to a collection param, then we do a "addAll" similar to: 
``` java 
// a) Action: _update b) param path points to collection c) payload is an array
collection.addAll();
```
The complex scenario is when the collection itself holds another collection as it's collection element. I think, we can take it step by step and add a check in Config Builder to throw InvalidConfigException if we detect Collection of Collection/Array till we can add support for it.

Another situation for _update would be:
```java
// a) Action: _update b) param path points to collection c) payload is not an array
collection.add();
```

In the example that you have given, if the collection already had [1, 2, 3], then submitting another _update with [1, 3] can result into:
a) [1, 2, 3, 1, 3] - this would be the case if hashcode & equals on the element treats the subsequent 1 & 3 as different identities than the original 1 & 3.
b) [1, 2, 3] - if the hashcode & equals matches to those in existing. 

To handle replacing with 1, 3, I would consider using _replace as the action:
```java
// a) Action: _replace b) param path points to collection c) payload is an array
collection.removeAll();
collection.addAll();
```

The other way to achieve the same would be using _delete:
```java
// a) Action: _delete b)param path point to collection _element_ c) payload is not array
collection.remove();
```

**Comment by lopezton-anthem** [comment]
Ok. I'll add the `addAll()` implementation in as a scenario.  To confirm our final list of scenarios:

**Scenario 1:** _param path is a leaf param_
  _update would be treated same as _replace, i.e., just set the state of leaf param

**Scenario 2:** _param path is a nested param_
  parse payload to an instance of object represented by the path. Traverse existing nested object's parameters and recursively apply partial update on each param found in payload. Surgical update would happen for leaf elements directly present in the nested object. All other elements within the model would get replaced (collections, nested params)

**Scenario 3:** _param path is a collection param and given json is a collection element_
  _update would be treated as an add of element to an existing collection

**Scenario 4:** _param path is a collection param and given json is an array of collection elements_
  _update would be treated as an `addAll` of elements to an existing collection

**Scenario 5:** _param path is a collection element param_
  _update would be treated same as _update to a nested param

**Comment by lopezton-anthem** [comment]
@soham-anthem Will you please review the updates to accommodate the scenarios we discussed?

**Pull request merged**
