### PR TITLE
Merge Nexus Updates into Latest

### PR DESCRIPTION
**Pull request by lopezton-anthem**
# Description

Merging Web Teks updates for Nexus release artifact build into latest.

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @lopezton-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by syamwebteks** [comment]
> @syamwebteks There is an error when running the build locally that gpg is not able to be found. Can you take a look at this?

@lopezton-anthem Which branch i should check in the change?

**Comment by lopezton-anthem** [comment]
> @lopezton-anthem Which branch i should check in the change?

@syamwebteks this branch is fine.

**Comment by syamwebteks** [comment]
> > @lopezton-anthem Which branch i should check in the change?
> 
> @syamwebteks this branch is fine. You can submit a PR to this branch and I can verify.

@lopezton-anthem But pom changes are not available in 1.1.x branch.

**Comment by lopezton-anthem** [comment]
@syamwebteks You can submit a pull request to [lopezton-anthem/nimbus-core/merge/nexus-updates](https://github.com/lopezton-anthem/nimbus-core/tree/merge/nexus-updates).  This branch has the pom updates.

**Comment by syamwebteks** [comment]
> @syamwebteks You can submit a pull request to [lopezton-anthem/nimbus-core/merge/nexus-updates](https://github.com/lopezton-anthem/nimbus-core/tree/merge/nexus-updates). This branch has the pom updates.

Pushed fix to this repo now it should be good in local build.

**Comment by lopezton-anthem** [comment]
@syamwebteks 

👍 Looks good to me... build is passing.

@dinakarmeda this is ready to be merged.

**Pull request merged**
