### PR TITLE
NIMBUS-112:: Support Multiple MongoDB Databases and Schemas

### PR DESCRIPTION
**Pull request by lopezton-anthem**
# Description

* Introduced new `@Repo` value: `Database.rep_custom`
  * Adds support for configuring customized repository implementations.
  * A sample multiple mongo db connection can be seen in `com.antheminc.oss.nimbus.test.scenarios.multidb.MultipleMongoDBTest`
  * Any custom repo implementation can be used, provided the necessary _Spring Beans_ are created.

# Overview of Changes

* Removed `ModelPersistenceHandler` for redundancy. Existing callers now directly call `ModelRepository` implementations.
  * This is subset of the delta introduced in [this change already in `2.0.x`](https://github.com/openanthem/nimbus-core/commit/b0aa1cc72e9fe71c02652a8814159e9d37a0ba83)
* Substantial changes to `DefaultMongoModelRepository`
  * `ModelRepositoryOptions` created to encapsulate repository behaviors
    * Search Operations
      * Search Operations are configurable by providing a custom `ModelRepositoryOptions`
      * _searchByQuery_ is no longer a spring bean
      * _searchByExample_ is no longer a spring bean
  * `MongoIdSequenceRepository`
    * `MongoIdSequenceRepository` is configurable during instantiation and is no longer a spring bean

# Type of Change

- [ ] New feature
- [ ] Refactor/Technical Debt
- [ ] Documentation Update

# Test Details

* Existing Test Cases
* `MultipleMongoDBTest.java`

# Additional Notes

N/A

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @lopezton-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by lopezton-anthem** [comment]
As there are several refactoring changes here, I would recommend reviewing the individual commits. I made sure to keep each commit as a separate, logical, and reviewable unit.

**Comment by lopezton-anthem** [comment]
> @lopezton-anthem I think we should not bring the complete repository changes from 2.0.x down like ModelRepository interface contract change etc...
> I was just referring to the part of if we want to remove the mongohandler class and directly call mongomodelrepository, just that change (not as is with other changes) but changes in terms of atomic handler can directly call modelrepository instead of going through handler class in between.

@rakeshnpatel I've changed the included commit to only remove the handler implementation. Can you review that change?

Let me know if you see an issue with any of the other refactoring I did. These refactorings are not already in `2.0.x`.

**Comment by openanthem-admin** [comment]
You did it @lopezton-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by lopezton-anthem** [comment]
`rep_custom[beanName]` syntax is not needed. Need to make change to just pass whatever bean name directly from the entity definition.

**Pull request merged**
