### PR TITLE
NIMBUS-2 Cross domain path variable resolver 

### PR DESCRIPTION
**Pull request by swethavemuri-anthem**
# Description
Capability for DomainPathResolver to resolve cross domain paths. 

# Overview of Changes
Added a check in DefaultCommandPathVariableResolver to resolve cross domain paths.
Ex: `@Config(url="/attr3/_replace?rawPayload=\"<!/p/sample_crossdomain_pathresolver/nested/attr_1!>\"")`

# Type of Change
- [ ] New feature
- [ ] Documentation Update
- [ ] Test case change
- [ ] This change requires a documentation update

# Test Details
CrossDomainPathResolverTest.java

# Additional Notes

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @swethavemuri-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by openanthem-admin** [comment]
You did it @swethavemuri-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by openanthem-admin** [comment]
You did it @swethavemuri-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by swethavemuri-anthem** [comment]
Closing because of JIRA check inconsistency

**Pull request closed without merging**
