### PR TITLE
hook to override bootstrap

### PR DESCRIPTION
**Pull request by vivekkamineni2018**
1.  Added a hook to override Bootstrap variables.
2. Changed the config to point to Bootstrap scss instead of css as variables does not exist outside the scope of Sass.

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @vivekkamineni2018!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by lopezton-anthem** [comment]
:+1:

**Comment by dinakarmeda** [comment]
@vivekkamineni2018 shouldn't this go in the nimbus-sass-module project?

**Comment by vivekkamineni2018** [comment]
This will be included in nm-sass-module as Dinakar suggested.   Closing this PR..

**Pull request closed without merging**
