### PR TITLE
NIMBUS-268: ParamValues Cache

### LINKED ISSUE #566: Request to improve performance on ParamValues Lookup from Cache
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
If a view domain has many `@Page` components, which have many `@Values` configurations that are using `staticCodeValue` lookup via `DefaultSearchFunctionHandlerLookup`, a `@Config` execution is performed to retrieve the cached value, taking a long time when many executions are performed.

## Expected Behavior
The execution should be more performant, perhaps by moving the attempt to retrieve from cache earlier in the execution process.

### Steps to Reproduce
1. Load a page that contains the code snippet below
2. Observe that multiple `@Config` executions are called for a single values retrieval.

Multiply this by many and we have performance issues

### Code Snippet
```java
@Label("Size of Pet")
@Values(url = "/p/staticCodeValue/_search?fn=lookup&where=staticCodeValue.paramCode.eq('/petSize')")
@ComboBox
private String size;
		
@Label("Size of Pet 2")
@Values(url = "/p/staticCodeValue/_search?fn=lookup&where=staticCodeValue.paramCode.eq('/petSize')")
@ComboBox
private String size2;
```

# Environment Details
* **Nimbus Version:**
1.3.1.M4

* **Browser:**
Google Chrome

### PR DESCRIPTION
**Pull request by lopezton-anthem**
# Description
Fixes #566 

# Overview of Changes
* Invokes the `staticCodeValues` cache prior to `@Config` execution
* Introduced new constants

# Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Refactor/Technical Debt
- [ ] Documentation Update
- [ ] Test case change
- [ ] This change requires a documentation update
- [ ] Other

# Test Details

N/A

# Additional Notes

N/A

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @lopezton-anthem!

Thank you for signing the Anthem Opensource Software CLA.

**Comment by lopezton-anthem** [comment]
This did show better performance results according to the consuming application team, however; they are not always using the `_search?fn=lookup` function handler, and so I don't think explicitly looking for this function handler in the DSL is the correct way to apply the cache retrieval.

@jayantchaudhuri thoughts?

**Comment by jayantchaudhuri** [comment]
> This did show better performance results according to the consuming application team, however; they are not always using the `_search?fn=lookup` function handler, and so I don't think explicitly looking for this function handler in the DSL is the correct way to apply the cache retrieval.
> 
> @jayantchaudhuri thoughts?

Right. Would it make more sense to add an attribute to @Value that takes the static code query? We apply the cache logic only on this attribute and let normal command url processing remain the way it is.

**Comment by lopezton-anthem** [comment]
> Right. Would it make more sense to add an attribute to @value that takes the static code query? We apply the cache logic only on this attribute and let normal command url processing remain the way it is.

@jayantchaudhuri, that would work, but I think the application would have a lot of refactoring.

I like the configuration approach. How about adding a flag like `boolean useParamValuesCacheOnLoad` in `@Values` and default it to be `true`?  This still allows the retrieval via the `url` attribute, but we just check if it's a `staticCodeValue` domain and the `useParamValuesCacheOnLoad` to apply the new retrieve from cache logic?

**Comment by jayantchaudhuri** [comment]
> > Right. Would it make more sense to add an attribute to @value that takes the static code query? We apply the cache logic only on this attribute and let normal command url processing remain the way it is.
> 
> @jayantchaudhuri, that would work, but I think the application would have a lot of refactoring.
> 
> I like the configuration approach. How about adding a flag like `boolean useParamValuesCacheOnLoad` in `@Values` and default it to be `true`? This still allows the retrieval via the `url` attribute, but we just check if it's a `staticCodeValue` domain and the `useParamValuesCacheOnLoad` to apply the new retrieve from cache logic?

That makes sense. I think that will be a good approach

**Comment by lopezton-anthem** [comment]
@jayantchaudhuri I think it's all wrapped up here. Let me know if you have any issues.

**Pull request merged**
